"""Add_Master_AI_Control

Revision ID: 297339505d15
Revises: 8019447a429e
Create Date: 2026-06-20 01:19:18.808083
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297339505d15'
down_revision: Union[str, None] = '8019447a429e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_ai_provider', sa.String(length=20), server_default='gemini', nullable=False))
        batch_op.add_column(sa.Column('preferred_ai_model', sa.String(length=50), server_default='gemini-2.5-flash', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_ai_model')
        batch_op.drop_column('preferred_ai_provider')

    # ### end Alembic commands ###
