"""Add_Required_Skills_Tables

Revision ID: 8019447a429e
Revises: 1bf4a085c8f6
Create Date: 2026-06-20 01:16:19.052298
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8019447a429e'
down_revision: Union[str, None] = '1bf4a085c8f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_required_skills',
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('target_id', 'skill_name')
    )
    op.create_table('task_required_skills',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'skill_name')
    )
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_column('required_skills')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('required_skills')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skills', sa.VARCHAR(length=500), nullable=True))

    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skills', sa.VARCHAR(length=500), nullable=True))

    op.drop_table('task_required_skills')
    op.drop_table('target_required_skills')
    # ### end Alembic commands ###
