"""Add created_by and updated_by to goal and target

Revision ID: 9cc7cd41bd9c
Revises: ea92b5d04b17
Create Date: 2026-06-22 11:48:18.538530
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc7cd41bd9c'
down_revision: Union[str, None] = 'ea92b5d04b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_goals_updated_by_users', 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key('fk_goals_created_by_users', 'users', ['created_by'], ['id'])

    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_targets_updated_by_users', 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key('fk_targets_created_by_users', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_targets_updated_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_targets_created_by_users', type_='foreignkey')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_goals_updated_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_goals_created_by_users', type_='foreignkey')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
